sharefun/forms.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, TextField, PasswordField, SelectField, TextAreaField, BooleanField, ValidationError
from wtforms.validators import DataRequired, Length, EqualTo, Email

from models import Work, User


class RegisterForm(Form):

    email = StringField(
        '邮箱*', description='未注册过的邮箱', validators=[DataRequired('邮箱不能为空'), Length(1, 64), Email('邮箱格式不正确')])
    username = TextField(
        '昵称*', description='未被使用过的昵称', validators=[DataRequired('昵称不能为空'), Length(1, 64)])
    password = PasswordField('密码*', validators=[
        DataRequired('密码不能为空'),
        EqualTo('confirm', message='密码不一致，请重新输入密码')]
    )
    confirm = PasswordField(
        '确认*', description='重复输入密码确认', validators=[DataRequired('密码不能为空')])

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已经被注册过，请更换邮箱')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已经被使用，请更换用户名')


class SigninForm(Form):

    email = StringField(
        '邮箱*', description='使用已注册过的邮箱', validators=[DataRequired('邮箱不能为空'), Length(1, 64), Email('邮箱格式不正确')])
    password = PasswordField('密码*', validators=[DataRequired('密码不能为空')])
    remember_me = BooleanField('记住我')
    submit = SubmitField('登陆')


class WorkForm(Form):

    cate_id = SelectField(
        '类别', default=1, validators=[DataRequired('作品类别不能为空')], coerce=int)
    title1 = TextField('作品1', description='准确的作品名称')
    title2 = TextField('作品2', description='准确的作品名称')
    title3 = TextField('作品3', description='准确的作品名称')
    title4 = TextField('作品4', description='准确的作品名称')
    title5 = TextField('作品5', description='准确的作品名称')

    recomm_reason1 = TextField('推荐词', description='选填')
    recomm_reason2 = TextField('推荐词', description='选填')
    recomm_reason3 = TextField('推荐词', description='选填')
    recomm_reason4 = TextField('推荐词', description='选填')
    recomm_reason5 = TextField('推荐词', description='选填')


class CommentForm(Form):

    content = TextAreaField(
        '内容', description='知道啥说啥,支持吐槽,鼠标移到右下角点击移动拖大此框,支持markdown', validators=[DataRequired('评论内容不能为空')])


class SingleRecommendationForm(Form):

    name = TextField('作品名称')
    remarks = TextField('审核备注')
    recomm_reason = TextField('推荐原因')

    cate_id = SelectField('作品类别',  coerce=int)
    status_id = SelectField('推荐状态',  coerce=int)
    user_id = SelectField('推荐人',   coerce=int)


class SignupForm(Form):

    """Form for send email"""
    email = TextField('邮箱', [DataRequired(message="邮箱不能为空"), Email(message="无效的邮箱")],
                      description='你常用的邮箱')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已经被注册过，请更换邮箱')

sharefun/__init__.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask import Flask, request, url_for, render_template, g, session, flash
from flask_wtf.csrf import CsrfProtect
from flask_debugtoolbar import DebugToolbarExtension
from flask.ext.login import LoginManager
from flask.ext.moment import Moment

from . import filters, permissions
from .utils import signout_user
from .config import load_config

config = load_config()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.signin'
login_manager.login_message = '请先登陆以获得相应操作权限'

# convert python's encoding to utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')


def register_login_manager(app):
    """注册login_manager"""
    login_manager.init_app(app)


def register_jinja(app):

    # inject vars into template context
    @app.context_processor
    def inject_vars():
        from .models import Category
        from datetime import date
        year = date.today().strftime("%Y")
        return dict(Permission=permissions.Permission, categories=Category.query.all(), year=year)

    # url generator for pagination
    def url_for_other_page(page):
        """Generate url for pagination"""
        view_args = request.view_args.copy()
        args = request.args.copy().to_dict()
        combined_args = dict(view_args.items() + args.items())
        combined_args['page'] = page
        return url_for(request.endpoint, **combined_args)
        # same effect
        # args = request.args.copy()
        # args['page'] = page
        # return url_for(request.endpoint, **args)

    app.jinja_env.globals['url_for_other_page'] = url_for_other_page


def register_routes(app):
    from .controllers import admin, site, user, auth
    app.register_blueprint(site.bp, url_prefix='')
    app.register_blueprint(admin.bp, url_prefix='/admin')
    app.register_blueprint(user.bp, url_prefix='/user')
    app.register_blueprint(auth.bp, url_prefix='/auth')


def register_error_handle(app):
    @app.errorhandler(403)
    def page_403(error):
        return render_template('site/403.html'), 403

    @app.errorhandler(404)
    def page_404(error):
        return render_template('site/404.html'), 404

    @app.errorhandler(405)
    def page_405(error):
        return render_template('site/405.html'), 405

    @app.errorhandler(500)
    def page_500(error):
        return render_template('site/500.html'), 500


def register_db(app):
    from .models import db
    db.init_app(app)


def register_mail(app):
    from .utils import mail
    mail.init_app(app)


def get_mail_handler():
    import logging
    from logging.handlers import SMTPHandler
    credentials = (config.SMTP_USER, config.SMTP_PASSWORD)
    mail_handler = SMTPHandler(config.SMTP_SERVER, config.SMTP_FROM,
                               config.SMTP_ADMIN, 'sf-log', credentials, ())
    from logging import Formatter
    mail_handler.setFormatter(Formatter('''
        Message type:       %(levelname)s
        Location:           %(pathname)s:%(lineno)d
        Module:             %(module)s
        Function:           %(funcName)s
        Time:               %(asctime)s

        Message:

        %(message)s
    '''))
    mail_handler.setLevel(logging.ERROR)
    return mail_handler


def register_logger(app):
    """send error log to admin by smtp"""
    if not app.debug:
        app.logger.addHandler(get_mail_handler())


def register_moment(app):
    moment = Moment(app)


def get_current_user():
    """获取当前user，同时进行session有效性的检测
       放在utils.py会造成环路引用
    """
    # 对应utils.py中signin_user方法
    # 豆瓣登陆则验证邮箱, 非豆瓣登陆不验证邮箱直接返回空值退出
    if 'signin_method' not in session:
        return None
    if 'user_id' not in session:
        return None
    # else:
    #     for k,v in session.iteritems():
    #         print k,v
    from .models import User
    # 此处是user_id而不是douban_id
    user = User.query.filter(User.id == session['user_id']).first()
    if not user:
        signout_user()
        return None
    return user


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # CSRF protect
    CsrfProtect(app)

    if app.debug:
        DebugToolbarExtension(app)

    register_jinja(app)
    register_routes(app)
    register_error_handle(app)
    register_db(app)
    register_logger(app)
    register_login_manager(app)
    register_moment(app)
    register_mail(app)

    app.jinja_env.filters['markdown'] = filters.markdown
    app.jinja_env.filters['normalize'] = filters.normalize
    app.jinja_env.filters[
        'engrolename_chinrolename'] = filters.engrolename_chinrolename
    app.jinja_env.filters['ismyself'] = filters.ismyself

    @app.before_request
    def before_request():
        g.user = get_current_user()
        if g.user:
            if not g.user.is_activated:
                flash('账户尚未激活，请先登陆' + g.user.email + '查收验证邮件并激活账户')
                signout_user()
            if g.user.is_banned:
                flash('账户已被禁用, 请联系管理员')
                signout_user()

    return app

app = create_app()

sharefun/config/__init__.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

import os


def load_config():
    """加载配置类"""
    mode = os.environ.get('MODE')
    try:
        if mode == 'PRODUCTION':
            from .production import ProductionConfig
            return ProductionConfig
        elif mode == 'TESTING':
            from .testing import TestingConfig
            return TestingConfig
        else:
            from .development import DevelopmentConfig
            return DevelopmentConfig
    except ImportError, e:
        from .default import Config
        return Config

sharefun/controllers/__init__.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

sharefun/controllers/admin.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask import Blueprint, render_template, redirect, url_for, request,  session, flash
from flask.ext.login import login_user, logout_user, login_required

from ..forms import SigninForm, RegisterForm, SingleRecommendationForm
from ..models import db, Status, Recommendation, User, Category, work_genres, Work
from ..decorators import admin_required, permission_required

import datetime

bp = Blueprint('admin', __name__)

# 判断是否具有某一特定权限
# @permission_required(Permission.MODERATE_COMMENTS)


@bp.route('/recommendations/audit/')
@login_required
@admin_required
def audit():
    statusids_recommendations = [
        (s.id, s.recommendations) for s in Status.query.order_by(Status.id)]
    return render_template('site/recommendations.html', statusids_recommendations=statusids_recommendations)


@bp.route('/recommendation/edit/<int:recomm_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_recommendation(recomm_id):
    recommendation = Recommendation.query.get_or_404(recomm_id)
    form = SingleRecommendationForm(obj=recommendation)
    form.cate_id.choices = [(t.id, t.name)
                            for t in Category.query.order_by(Category.index)]
    form.status_id.choices = [(t.id, t.name)
                              for t in Status.query.order_by(Status.id)]
    form.user_id.choices = [(t.id, t.username)
                            for t in User.query.order_by(User.id)]
    if form.validate_on_submit():
        recommendation.name = form.name.data
        recommendation.remarks = form.remarks.data
        recommendation.recomm_reason = form.recomm_reason.data
        recommendation.cate_id = form.cate_id.data
        recommendation.status_id = form.status_id.data
        recommendation.user_id = form.user_id.data
        recommendation.finished = datetime.datetime.utcnow()
        db.session.add(recommendation)
        db.session.commit()
        return redirect(url_for('admin.audit'))
    return render_template('site/recommendation.html', form=form, recommendation=recommendation)


@bp.route('/recommendations/audit/<int:recomm_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def audit_recommenations(recomm_id):
    recommendation = Recommendation.query.get_or_404(recomm_id)
    """审核与真正处理数据中间相隔一定时间，所以将审核通过状态分为通过未上架（默认）和通过已上架，增加删除待审核推荐"""
    if 'hide' in request.form:
        # 如果对应作品已上架则删除对应的work_genres和work数据，如需要再通过审核重新下载
        if recommendation.status_id == 3:
            work = Work.query.filter_by(id=recommendation.work_id).first()
            genres = work.genres
            for genre in genres:
                work.genres.remove(genre)
            db.session.delete(work)
            db.session.commit()
        recommendation.status_id = 5      # 设置为隐藏无效状态
    if 'yes' in request.form:
        recommendation.status_id = 2
    if 'no' in request.form:
        recommendation.status_id = 4
    if 'yes-append' in request.form:
        recommendation.remarks = recommendation.remarks + \
            request.form.get('remarks')
    elif 'yes-modify' in request.form:
        recommendation.remarks = request.form.get('remarks')
    recommendation.finished = datetime.datetime.utcnow()
    db.session.add(recommendation)
    db.session.commit()
    return redirect(url_for('admin.audit'))

sharefun/controllers/site.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask import render_template, Blueprint, redirect, url_for, request, flash, current_app
from flask.ext.login import current_user

from ..forms import WorkForm, CommentForm
from ..models import db, Category, Work, Comment, Recommendation, Status, User, Genre, work_genres

import os
from datetime import datetime

bp = Blueprint('site', __name__)


@bp.route('/')
def index():
    """首页"""
    newest_works = []
    categories = Category.query.order_by(Category.id).all()
    for category in categories:
        all_works = Work.query.filter_by(
            cate_id=category.id).order_by(Work.created.desc()).all()
        count = len(all_works)
        works = all_works[:4] if len(all_works) >= 4 else all_works+['']*(4-len(all_works))
        newest_works.append([category, [count, works]])
    newest_comments = Comment.query.order_by(Comment.created.desc()).limit(5)
    total = Recommendation.query.count()
    success = Recommendation.query.filter(
        Recommendation.status_id == 3).count()
    failure = Recommendation.query.filter(
        Recommendation.status_id == 4).count()
    return render_template('site/index.html', newest_works=newest_works, newest_comments=newest_comments, current_time=datetime.utcnow(), total=total, success=success, failure=failure)


@bp.route('/category')
def category():
    """分类页"""
    genre_id = request.args.get('genre_id', 0, int)
    page = request.args.get('page', 1, int)
    cate_id = request.args.get('cate_id', 1, int)
    works = Work.query.filter_by(cate_id=cate_id)
    # 按照类型对应的作品数对类型排序
    from sqlalchemy import func
    genres = [genre for genre, count in db.session.query(Genre, func.count(work_genres.c.work_id).label(
        'total')).filter_by(cate_id=cate_id).join(work_genres).group_by(Genre).order_by('total desc').all()]
    if genre_id:
        if genre_id == -1:  # 随机
            works = works.order_by(func.rand())
        else:
            # use join
            # works = works.join(Genre.works).filter(Genre.id == genre_id)
            works = works.filter(Work.genres.any(id=genre_id)).order_by(
                Work.created.desc())
    else:
        works = works.order_by(Work.created.desc())

    # newest_comments = Comment.query.order_by(Comment.created.desc()).limit(5)
    newest_comments = Comment.query.join(Work).filter_by(cate_id=cate_id).order_by(Comment.created.desc()).limit(5)
    total = Recommendation.query.count()
    success = Recommendation.query.filter(
        Recommendation.status_id == 3).count()
    failure = Recommendation.query.filter(
        Recommendation.status_id == 4).count()
    works = works.paginate(
        page, current_app.config['FLASK_WORKS_PER_PAGE'], error_out=True)
    return render_template('site/category.html', works=works, newest_comments=newest_comments, current_time=datetime.utcnow(), total=total, success=success, failure=failure, genres=genres, genre_id=genre_id, page=page, cate_id=cate_id)


@bp.route('/about')
def about():
    """关于"""
    return render_template('site/about.html')


@bp.route('/work/<int:work_id>', methods=['GET', 'POST'])
def work(work_id):
    """详情页"""
    form = CommentForm()
    q = Work.query
    work = q.get_or_404(work_id)
    prev = q.filter(Work.id > work_id).order_by(Work.id).first()
    next = q.filter(Work.id < work_id).order_by(Work.id.desc()).first()
    genres = []
    for genre in work.genres:
        genres.append(genre)
    if form.validate_on_submit() and current_user.is_authenticated():
        content = form.content.data.strip()
        comment = Comment(
            content=content, user_id=current_user.id,  work_id=work.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('site.work', work_id=work.id))
    return render_template('site/work.html', work=work, form=form, genres=genres, prev=prev, next=next)


@bp.route('/user/<int:id>')
def user(id):
    user = User.query.get_or_404(id)
    success_recomms_count = Recommendation.query.filter(
        Recommendation.user_id == id, Recommendation.status_id == 3).count()
    comments_count = Comment.query.filter(Comment.user_id == id).count()
    return render_template('site/user.html', user=user, success_recomms_count=success_recomms_count, comments_count=comments_count)


@bp.route('/comments')
def comments():
    """所有评论页"""
    user_id = request.args.get('user_id', 0, int)
    page = request.args.get('page', 1, int)
    comments = Comment.query.order_by(Comment.created.desc())
    # 只显示有评论的user
    users = [user for user in User.query.all() if user.comments.count()]
    # 按照评论数量倒序对user排序
    users = sorted(
        users, lambda u1, u2: cmp(u1.comments.count(), u2.comments.count()), reverse=True)
    if user_id:
        comments = comments.filter(Comment.user_id == user_id)
    comments = comments.paginate(
        page, current_app.config['FLASK_COMMENTS_PER_PAGE'], error_out=True)
    return render_template('site/comments.html', comments=comments, users=users, user_id=user_id)


@bp.route('/recommendations')
def recommendations():
    statusids_recommendations = [
        (s.id, s.recommendations) for s in Status.query.order_by(Status.id)]
    return render_template('site/recommendations.html', statusids_recommendations=statusids_recommendations)


@bp.route('/search')
def search():
    keyword = request.args.get('keyword')
    if not keyword:
        flash('请输入要在本站搜索的作品名称')
        return redirect(url_for('site.index'))
    else:
        works = Work.query.filter(Work.title.like('%' + keyword + '%'))
        if not works.count():
            flash('抱歉，本站暂未收录与"' + keyword + '"相关的作品')
            return redirect(url_for('site.index'))
        else:
            return render_template('site/search.html', works=works, keyword=keyword)

sharefun/script/__init__.py
from ..config import load_config

config = load_config()

sharefun/templates/macro/common.html
{% macro pagination(paginator) %}
   {% if paginator.pages > 1 %}
      <ul class='pagination pagination-sm'>
         {% if paginator.has_prev %}
            <li><a href="{{ url_for_other_page(paginator.prev_num) }}">上一页</a></li>
         {% endif %}

         {% for page in paginator.iter_pages() %}
            {% if page %}
               {% if page != paginator.page %}
                  <li><a href="{{ url_for_other_page(page) }}">{{ page }}</a></li>
               {% else %}
                  <li class="active"><span>{{ page }}</span></li>
               {% endif %}
            {% else %}
               <li class="ellipsis"><span>...</span></li>
            {% endif %}
         {% endfor %}

         {% if paginator.has_next %}
            <li><a href="{{ url_for_other_page(paginator.next_num) }}">下一页</a></li>
         {% endif %}
      </ul>
   {% endif %}
{% endmacro %}

{% macro field_errors(field) %}
    {% if field.errors %}
        <ul class="list-form-errors text-danger list-unstyled">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}

{% macro horizontal_field(field, length=6, label=True) %}
    <div class="form-group">
        {% if label %}
            {{ field.label(class="col-md-2 control-label") }}
        {% endif %}

        <div class="col-md-{{ length }}">
            {{ field(class="form-control", placeholder=field.description, **kwargs) }}
            {{ field_errors(field) }}
        </div>
    </div>
{% endmacro %}

{% macro two_horizontal_field(field1, field2, length1=3, length2=5, label=True) %}
    <div class="form-group">
        {% if label %}
            {{ field1.label(class="col-md-2 control-label") }}
        {% endif %}
        <div class="col-md-{{ length1 }}">
            {{ field1(class="form-control", placeholder=field1.description, **kwargs) }}
            {{ field_errors(field1) }}
        </div>

        {% if label %}
            {{ field2.label(class="col-md-1 control-label") }}
        {% endif %}
        <div class="col-md-{{ length2 }}">
            {{ field2(class="form-control", placeholder=field2.description, **kwargs) }}
            {{ field_errors(field2) }}
        </div>
    </div>
{% endmacro %}

{% macro label_primary(field) %}
    <span class="label label-primary">
        {{ field }}
    </span>
{% endmacro %}
{% macro recommendation_to_work(field)  %}
    {% if field.work_id %}
        <a href="{{ url_for('site.work', work_id=field.work_id) }}">
            {{ field.name }}
        </a>
    {% else %}
            {{ field.name }}
    {% endif %}
{% endmacro %}

{% macro generate_table(t, recommendations) %}
    <h2>{{ t }}</h2>
    <hr/>
    {% if recommendations.count() %}
        <table class="table table-bordered">
            <tr>
                <td>名称</td>
                <td>类别</td>
                <td>推荐人</td>
                <td>提交时间</td>
                <td>审核备注</td>
                {% if current_user.is_authenticated() and current_user.is_administrator() %}
                    <td>审核</td>
                {% endif %}
                {% if t != '待审核' %}
                    <td>结束时间</td>
                {% endif %}
                {% if current_user.is_authenticated() and current_user.is_administrator() %}
                    <td></td>
                {% endif %}
            </tr>
            {% for recommendation in recommendations %}
                <tr>
                    {% if recommendation.status_id == 1 %}
                        <td>
                            <span class="larger label label-default">
                                {{ recommendation_to_work(recommendation) }}
                            </span>
                        </td>
                    {% elif recommendation.status_id == 2 %}
                        <td>
                            <span class="larger label label-info">
                                {{ recommendation_to_work(recommendation) }}
                            </span>
                        </td>
                    {% elif recommendation.status_id == 3 %}
                        <td>
                            <span class="larger label label-success">
                                {{ recommendation_to_work(recommendation) }}
                            </span>
                        </td>
                    {% elif recommendation.status_id == 4 %}
                        <td>
                            <span class="larger label label-danger">
                                {{ recommendation_to_work(recommendation) }}
                            </span>
                        </td>
                    {% else %}
                        <td class="larger">
                            {{ recommendation_to_work(recommendation) }}
                        </td>
                    {% endif %}
                    <td><a href="{{ url_for('site.category', cate_id=recommendation.cate_id) }}">{{ label_primary(recommendation.category.name) }}</a></td>
                    <td><a href="{{ url_for('site.user', id=recommendation.user.id) }}" target="_blank">{{ label_primary(recommendation.user.username | ismyself | normalize) }}</a></td>
                    <td><span class="label label-primary">{{ moment(recommendation.created).fromNow(refresh=True) }}</span></td>
                    <td>{{ label_primary(recommendation.remarks | normalize) }}</td>
                    {% if current_user.is_authenticated() and current_user.is_administrator() %}
                        <td>
                            <form method="post" action="{{ url_for('admin.audit_recommenations', recomm_id=recommendation.id) }}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                <div class="input-group input-group-sm" style="width: 300px;">
                                    <input type="text" name="remarks" class="form-control">
                                    <span class="input-group-btn">
                                    　　{% if recommendation.status_id == 2 or recommendation.status_id == 3 %}
                                            <input class="btn btn-default " type="submit" name="yes-modify" value="更新备注">
                                            <input class="btn btn-default " type="submit" name="yes-append" value="追加备注">
                                    　　{% elif recommendation.status_id == 4 %}
                                            <input class="btn btn-default" type="submit" name="yes" value="通过">
                                       {% elif recommendation.status_id == 1 %}
                                            <input class="btn btn-default" type="submit" name="yes" value="通过">
                                            <input class="btn btn-default" type="submit" name="no" value="不通过">
                                       {% endif %}

                                       {% if recommendation.status_id != 5 %}
                                            <input class="btn btn-default" type="submit" name="hide" value="隐藏">
                                       {% else %}
                                            <input class="btn btn-default" type="submit" name="yes" value="通过">
                                       {% endif %}
                                    </span>
                                </div>
                            </form>
                        </td>
                    {% endif %}
                    {% if recommendation.status_id != 1 %}
                        <td><span class="label label-primary">{{ moment(recommendation.finished).fromNow(refresh=True) }}</span></td>
                    {% endif %}
                    {% if current_user.is_authenticated() and current_user.is_administrator() %}
                        <td>
                             <form method="get" action="{{ url_for('admin.edit_recommendation', recomm_id=recommendation.id) }}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                <input class="btn btn-default" type="submit" name="edit_recommendation" value="修改">
                             </form>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h5 class="table">暂无</h5>
    {% endif %}
{% endmacro %}