sharefun/config/__init__.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

import os


def load_config():
    """加载配置类"""
    mode = os.environ.get('MODE')
    try:
        if mode == 'PRODUCTION':
            from .production import ProductionConfig
            return ProductionConfig
        elif mode == 'TESTING':
            from .testing import TestingConfig
            return TestingConfig
        else:
            from .development import DevelopmentConfig
            return DevelopmentConfig
    except ImportError, e:
        from .default import Config
        return Config

sharefun/controllers/__init__.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

sharefun/controllers/auth.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask import Blueprint, render_template, redirect, url_for, request,  session, flash, current_app
from flask.ext.login import login_user, logout_user, login_required

from ..forms import SigninForm, RegisterForm, SignupForm
from ..models import db, Status, Recommendation, User
from ..decorators import logout_required
from ..utils import signup_mail,  signin_user, signout_user

import datetime
import requests
import hashlib

bp = Blueprint('auth', __name__)


@bp.route('/register/', methods=['GET', 'POST'])
@logout_required
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('注册成功，请登陆')
        return redirect(url_for('auth.signin'))
    return render_template('auth/register.html', form=form)

# 说明：
# 登入系统有两种途径，一直接在本站注册登陆无需验证邮箱，直接登陆；二用豆瓣登陆，需验证邮箱
# 其中直接在本站注册登陆同样会将user_id存入session（login_user函数），豆瓣登陆将douban_id存入session的user_id(signin_user函数)中
#
# session中存储内容类似：
# csrf_token 05b2c11c12465135d664eb27ff79ceee45c275a7
# _fresh True
# user_id 39
# _id 7e987c7c53125f1d833c61e97033dd20
#
# 每次请求之前会检查当前登陆方式，如果是豆瓣登陆则会检查该账户是否被激活及是否被禁止，直接注册登陆不检查状态
# 直接注册登陆退出使用flask_login的logout_user，豆瓣登陆退出时使用signout_user


@bp.route('/signin', methods=['GET', 'POST'])
@logout_required
def signin():
    form = SigninForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('该邮箱尚未注册，请重新登陆')
            return render_template('auth/signin.html', form=form)
        if user is not None and user.verify_password(form.password.data):
            flash('欢迎登陆ShareFun')
            login_user(user, form.remember_me.data)
            return redirect(request.args.get('next') or url_for('site.index'))
        flash('邮箱或密码错误，请重新登陆')
    return render_template('auth/signin.html', form=form)


@bp.route('/douban_pre_signin')
@logout_required
def douban_pre_signin():
    config = current_app.config
    return redirect(config.get('DOUBAN_LOGIN_URL'))


@bp.route('/douban_signin')
@logout_required
def douban_signin():
    """通过豆瓣OAuth登陆
    user_id实际是User表中的douban_id字段
    """
    # get current authed user id
    code = request.args.get('code')
    print code
    if not code:
        return redirect(url_for('site.index'))
    url = "https://www.douban.com/service/auth2/token"
    config = current_app.config
    data = {
        'client_id': config.get('DOUBAN_CLIENT_ID'),
        'client_secret': config.get('DOUBAN_SECRET'),
        'redirect_uri': config.get('DOUBAN_REDIRECT_URI'),
        'grant_type': 'authorization_code',
        'code': code
    }
    res = requests.post(url, data=data).json()
    print res
    # 返回access_token类似：
    # {
    #   "access_token":"a14afef0f66fcffce3e0fcd2e34f6ff4",
    #   "expires_in":3920,
    #   "refresh_token":"5d633d136b6d56a41829b73a424803ec",
    #   "douban_user_id":"1221"
    # }
    if 'douban_user_id' not in res:
        return redirect(url_for('site.index'))

    user_id = int(res['douban_user_id'])
    user = User.query.filter_by(douban_id=user_id).first()
    if user:
        if user.is_banned:
            flash('账户已被禁用， 请联系管理员')
            signout_user()
            return redirect(url_for('site.index'))
        if not user.is_activated:
            flash('账户尚未激活，请先登陆' + user.email + '查收验证邮件激活账户')
            signout_user()
            return redirect(url_for('site.index'))

        flash('欢迎使用豆瓣账户登陆ShareFun')
        signin_user(user, True)
        redirect_url = url_for('site.index')

        user.access_token = res['access_token']
        db.session.add(user)
        db.session.commit()
        # 用户此次登录同步豆瓣上之前的附注到本站
        from celery_proj.tasks import sync_with_douban
        sync_with_douban.delay()

        return redirect(redirect_url)
    # 通过加密的session传递user_id数据，防止恶意注册
    session['signup_user_id'] = user_id
    return redirect(url_for('auth.douban_signup'))


@bp.route('/douban_signup', methods=['GET', 'POST'])
@logout_required
def douban_signup():
    """发送激活邮件
    user_id实际是User表中的douban_id字段
    """
    if not 'signup_user_id' in session:
        abort(403)

    user_id = int(session['signup_user_id'])
    user = User.query.filter_by(douban_id=user_id).first()
    if user:
        abort(403)

    # Get user info from douban
    url = "https://api.douban.com/v2/user/%d" % user_id
    user_info = requests.get(url).json()

#     print type(user_info)
# <type 'dict'>
#     print user_info
# {u'loc_id': u'118183', u'name': u'fansion', u'created': u'2011-10-13 01:16:09', u'id': u'55005354', u'is_suicide': False, u'large_avatar': u'http://img3.douban.com/icon/up55005354-2.jpg', u'avatar': u'http://img3.douban.com/icon/u55005354-2.jpg', u'signature': u'\u4f60\u7231\u6216\u4e0d\u7231\uff0c\u5c0f\u7231\u5c31\u5728\u8fd9\u91cc\u3002', u'loc_name': u'\u5b89\u5fbd\u5408\u80a5', u'is_banned': False, u'desc': u'\u4e00\u76f4\u5728\u8def\u4e0a\u3002\n\nBLOG: http://ifanan.com', u'type': u'user', u'alt': u'http://www.douban.com/people/xiaoaifansion/', u'uid': u'xiaoaifansion'}

    form = SignupForm()
    if form.validate_on_submit():
        to_addr = form.email.data
        user = User(
            douban_id=user_id, username=user_info['name'], email=to_addr, douban_abbr=user_info['uid'])
        db.session.add(user)
        db.session.commit()
        # send activate email
        try:
            signup_mail(user)
        except:
            flash('邮件发送失败，请稍后尝试')
        else:
            flash('激活邮件已发送到你的邮箱，请查收激活')
        signout_user()
        session.pop('signup_user_id')
        return redirect(url_for('site.index'))
    return render_template('auth/douban_signup.html', user_info=user_info, form=form)


@bp.route('/activate/<int:douban_id>/<token>')
@logout_required
def douban_activate(douban_id, token):
    # douban_id和token在链接中顺序不影响
    user = User.query.filter_by(douban_id=douban_id).first()
    if token == hashlib.sha1(user.username).hexdigest():
        user.is_activated = True
        db.session.add(user)
        db.session.commit()
        signin_user(user, True)
        flash('账号激活成功，欢迎光临ShareFun')
        return redirect(url_for('site.index'))
    flash('无效的激活链接')
    return redirect(url_for('site.index'))


@bp.route('/signout/')
@login_required
def signout():
    logout_user()
    flash('成功登出,欢迎再次登入')
    return redirect(url_for('site.index'))

sharefun/controllers/site.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask import render_template, Blueprint, redirect, url_for, request, flash, current_app
from flask.ext.login import current_user

from ..forms import WorkForm, CommentForm
from ..models import db, Category, Work, Comment, Recommendation, Status, User, Genre, work_genres

import os
from datetime import datetime

bp = Blueprint('site', __name__)


@bp.route('/')
def index():
    """首页"""
    newest_works = []
    categories = Category.query.order_by(Category.id).all()
    for category in categories:
        all_works = Work.query.filter_by(
            cate_id=category.id).order_by(Work.created.desc()).all()
        count = len(all_works)
        works = all_works[:4] if len(all_works) >= 4 else all_works+['']*(4-len(all_works))
        newest_works.append([category, [count, works]])
    newest_comments = Comment.query.order_by(Comment.created.desc()).limit(5)
    total = Recommendation.query.count()
    success = Recommendation.query.filter(
        Recommendation.status_id == 3).count()
    failure = Recommendation.query.filter(
        Recommendation.status_id == 4).count()
    return render_template('site/index.html', newest_works=newest_works, newest_comments=newest_comments, current_time=datetime.utcnow(), total=total, success=success, failure=failure)


@bp.route('/category')
def category():
    """分类页"""
    genre_id = request.args.get('genre_id', 0, int)
    page = request.args.get('page', 1, int)
    cate_id = request.args.get('cate_id', 1, int)
    works = Work.query.filter_by(cate_id=cate_id)
    # 按照类型对应的作品数对类型排序
    from sqlalchemy import func
    genres = [genre for genre, count in db.session.query(Genre, func.count(work_genres.c.work_id).label(
        'total')).filter_by(cate_id=cate_id).join(work_genres).group_by(Genre).order_by('total desc').all()]
    if genre_id:
        if genre_id == -1:  # 随机
            works = works.order_by(func.rand())
        else:
            # use join
            # works = works.join(Genre.works).filter(Genre.id == genre_id)
            works = works.filter(Work.genres.any(id=genre_id)).order_by(
                Work.created.desc())
    else:
        works = works.order_by(Work.created.desc())

    # newest_comments = Comment.query.order_by(Comment.created.desc()).limit(5)
    newest_comments = Comment.query.join(Work).filter_by(cate_id=cate_id).order_by(Comment.created.desc()).limit(5)
    total = Recommendation.query.count()
    success = Recommendation.query.filter(
        Recommendation.status_id == 3).count()
    failure = Recommendation.query.filter(
        Recommendation.status_id == 4).count()
    works = works.paginate(
        page, current_app.config['FLASK_WORKS_PER_PAGE'], error_out=True)
    return render_template('site/category.html', works=works, newest_comments=newest_comments, current_time=datetime.utcnow(), total=total, success=success, failure=failure, genres=genres, genre_id=genre_id, page=page, cate_id=cate_id)


@bp.route('/about')
def about():
    """关于"""
    return render_template('site/about.html')


@bp.route('/work/<int:work_id>', methods=['GET', 'POST'])
def work(work_id):
    """详情页"""
    form = CommentForm()
    q = Work.query
    work = q.get_or_404(work_id)
    prev = q.filter(Work.id > work_id).order_by(Work.id).first()
    next = q.filter(Work.id < work_id).order_by(Work.id.desc()).first()
    genres = []
    for genre in work.genres:
        genres.append(genre)
    if form.validate_on_submit() and current_user.is_authenticated():
        content = form.content.data.strip()
        comment = Comment(
            content=content, user_id=current_user.id,  work_id=work.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('site.work', work_id=work.id))
    return render_template('site/work.html', work=work, form=form, genres=genres, prev=prev, next=next)


@bp.route('/user/<int:id>')
def user(id):
    user = User.query.get_or_404(id)
    success_recomms_count = Recommendation.query.filter(
        Recommendation.user_id == id, Recommendation.status_id == 3).count()
    comments_count = Comment.query.filter(Comment.user_id == id).count()
    return render_template('site/user.html', user=user, success_recomms_count=success_recomms_count, comments_count=comments_count)


@bp.route('/comments')
def comments():
    """所有评论页"""
    user_id = request.args.get('user_id', 0, int)
    page = request.args.get('page', 1, int)
    comments = Comment.query.order_by(Comment.created.desc())
    # 只显示有评论的user
    users = [user for user in User.query.all() if user.comments.count()]
    # 按照评论数量倒序对user排序
    users = sorted(
        users, lambda u1, u2: cmp(u1.comments.count(), u2.comments.count()), reverse=True)
    if user_id:
        comments = comments.filter(Comment.user_id == user_id)
    comments = comments.paginate(
        page, current_app.config['FLASK_COMMENTS_PER_PAGE'], error_out=True)
    return render_template('site/comments.html', comments=comments, users=users, user_id=user_id)


@bp.route('/recommendations')
def recommendations():
    statusids_recommendations = [
        (s.id, s.recommendations) for s in Status.query.order_by(Status.id)]
    return render_template('site/recommendations.html', statusids_recommendations=statusids_recommendations)


@bp.route('/search')
def search():
    keyword = request.args.get('keyword')
    if not keyword:
        flash('请输入要在本站搜索的作品名称')
        return redirect(url_for('site.index'))
    else:
        works = Work.query.filter(Work.title.like('%' + keyword + '%'))
        if not works.count():
            flash('抱歉，本站暂未收录与"' + keyword + '"相关的作品')
            return redirect(url_for('site.index'))
        else:
            return render_template('site/search.html', works=works, keyword=keyword)

sharefun/controllers/user.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask import render_template, Blueprint, redirect, url_for,  flash
from flask.ext.login import login_required, current_user

from ..forms import WorkForm, CommentForm
from ..models import db, Category,  Comment, Recommendation, User

bp = Blueprint('user', __name__)


@bp.route('/secret')
@login_required
def secret():
    return 'Secret'


@bp.route('/recommend', methods=['GET', 'POST'])
def recommend():
    form = WorkForm()
    form.cate_id.choices = [(t.id, t.name)
                            for t in Category.query.order_by(Category.index)]
    if form.validate_on_submit():
        names = [form.title1.data.strip(), form.title2.data.strip(
        ), form.title3.data.strip(), form.title4.data.strip(), form.title5.data.strip()]
        recomm_reasons = [form.recomm_reason1.data.strip(), form.recomm_reason2.data.strip(
        ), form.recomm_reason3.data.strip(), form.recomm_reason4.data.strip(), form.recomm_reason5.data.strip()]
        cate_id = form.cate_id.data
        hasName = False
        hasRepetition = False
        repeatedNames = ' '
        for name in names:
            if name:
                # 判断是否存在
                if not Recommendation.query.filter(Recommendation.cate_id == cate_id).filter(Recommendation.name == name).first():
                    if current_user.is_authenticated():
                        recommendation = Recommendation(
                            name=name, cate_id=cate_id, remarks='', user_id=current_user.id, recomm_reason=recomm_reasons[names.index(name)])
                    else:
                        anonymous_user = User.query.filter_by(username='匿名').first()
                        if anonymous_user:
                            recommendation = Recommendation(
                                name=name, cate_id=cate_id, remarks='', user_id=anonymous_user.id, recomm_reason=recomm_reasons[names.index(name)])
                        else:
                            u = User(username='匿名')
                            db.session.add(u)
                            db.session.commit()
                            recommendation = Recommendation(
                                name=name, cate_id=cate_id, remarks='', user_id=u.id, recomm_reason=recomm_reasons[names.index(name)])
                    db.session.add(recommendation)
                else:
                    if name not in repeatedNames:
                        repeatedNames += '<<' + name + '>>'
                    hasRepetition = True
                hasName = True
        if hasRepetition:
            # 清空表单
            form.title1.data = form.title2.data = form.title3.data = form.title4.data = form.title5.data = ''
            form.recomm_reason1.data = form.recomm_reason2.data = form.recomm_reason3.data = form.recomm_reason4.data = form.recomm_reason5.data = ''

            flash(repeatedNames + '曾被推荐过,再提交些新鲜货吧亲')
            return render_template('user/recommend.html', form=form)
        if not hasName:
            flash(repeatedNames + '至少推荐一些再提交吧亲')
            return render_template('user/recommend.html', form=form)
        db.session.commit()
        return redirect(url_for('site.recommendations'))
    if not current_user.is_authenticated():
        flash('建议先注册，之后再推荐作品')
    return render_template('user/recommend.html', form=form)

sharefun/script/__init__.py
from ..config import load_config

config = load_config()

sharefun/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block page_title%}{% endblock %}</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}
    {% endblock %}">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    {% block meta %}
    {% endblock %}
    <link rel="icon" href="{{ url_for('static', filename='imgs/favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/bootstrap.theme.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/component.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/page.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/font-awesome.min.css') }}">
    <script src="{{ url_for('static', filename='js/respond.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_jquery() }}
    {{ moment.include_moment() }}
    {{ moment.lang('zh-cn') }}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-46259168-3', 'auto');
      ga('send', 'pageview');

    </script>
</head>
<body id="{% block page_id %}{% endblock %}">
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".my-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('site.about') }}">享乐
                <small class="small">享你所乐</small>
            </a>
        </div>
        <div class="collapse navbar-collapse my-navbar-collapse">
            <ul class="nav navbar-nav">
                {% if categories %}
                  {% for category in categories %}
                    <li><a href="{{ url_for('site.category', cate_id=category.id) }}">{{ category.name }}</a></li>
                  {% endfor %}
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <!--
                 <form class="nav navbar-nav navbar-form" role="search" method="get" action="{{ url_for('site.search') }}">
                    <input type="text" name="keyword" class="form-control input-sm"
                           placeholder="电影名/图书名/电视剧名">
                    <button class="btn btn-default btn-sm" type="submit" title="搜索">
                       <span class="fa fa-search"></span>
                    </button>
                 </form> -->
                 {% if current_user.is_authenticated() %}
                    {% if current_user.is_administrator() %}
                      <li><a href="{{ url_for('admin.audit') }}"><i class="fa fa-pencil"></i>审核</a></li>
                    {% else %}
                      <li><a href="{{ url_for('user.recommend') }}"><i class="fa fa-plus"></i>我要推荐</a></li>
                      <li><a href="{{ url_for('site.recommendations') }}"><i class="fa fa-list"></i>所有推荐</a></li>
                    {% endif %}
                    <li><a href="{{ url_for('auth.signout') }}"><i class="fa fa-sign-out"></i>登出</a></li>
                 {% else %}
                    <li><a href="{{ url_for('user.recommend') }}"><i class="fa fa-plus"></i>我要推荐</a></li>
                    <li><a href="{{ url_for('site.recommendations') }}"><i class="fa fa-list"></i>所有推荐</a></li>
                    <li><a href="{{ url_for('auth.signin') }}"><i class="fa fa-sign-in"></i>登陆</a></li>
                 {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div id="main-wap" class="container">
   {% block body %}{% endblock %}
</div>

<div id="footer">
   <div class='container'>
      <div id='copyright'>
         ShareFun©2014~{{ year }}
      </div>

      <ul id='links'>
         <li>
            <a href="https://github.com/Fansion/sharefun" target="_blank">独不如众乐乐</a>
        　</li>
      </ul>
   </div>
</div>

</body>
</html>