sharefun/forms.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, TextField, PasswordField, SelectField, TextAreaField, BooleanField, ValidationError
from wtforms.validators import DataRequired, Length, EqualTo, Email

from models import Work, User


class RegisterForm(Form):

    email = StringField(
        '邮箱*', description='未注册过的邮箱', validators=[DataRequired('邮箱不能为空'), Length(1, 64), Email('邮箱格式不正确')])
    username = TextField(
        '昵称*', description='未被使用过的昵称', validators=[DataRequired('昵称不能为空'), Length(1, 64)])
    password = PasswordField('密码*', validators=[
        DataRequired('密码不能为空'),
        EqualTo('confirm', message='密码不一致，请重新输入密码')]
    )
    confirm = PasswordField(
        '确认*', description='重复输入密码确认', validators=[DataRequired('密码不能为空')])

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已经被注册过，请更换邮箱')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已经被使用，请更换用户名')


class SigninForm(Form):

    email = StringField(
        '邮箱*', description='使用已注册过的邮箱', validators=[DataRequired('邮箱不能为空'), Length(1, 64), Email('邮箱格式不正确')])
    password = PasswordField('密码*', validators=[DataRequired('密码不能为空')])
    remember_me = BooleanField('记住我')
    submit = SubmitField('登陆')


class WorkForm(Form):

    cate_id = SelectField(
        '类别', default=1, validators=[DataRequired('作品类别不能为空')], coerce=int)
    title1 = TextField('作品1', description='准确的作品名称')
    title2 = TextField('作品2', description='准确的作品名称')
    title3 = TextField('作品3', description='准确的作品名称')
    title4 = TextField('作品4', description='准确的作品名称')
    title5 = TextField('作品5', description='准确的作品名称')

    recomm_reason1 = TextField('推荐词', description='选填')
    recomm_reason2 = TextField('推荐词', description='选填')
    recomm_reason3 = TextField('推荐词', description='选填')
    recomm_reason4 = TextField('推荐词', description='选填')
    recomm_reason5 = TextField('推荐词', description='选填')


class CommentForm(Form):

    content = TextAreaField(
        '内容', description='知道啥说啥,支持吐槽,鼠标移到右下角点击移动拖大此框,支持markdown', validators=[DataRequired('评论内容不能为空')])


class SingleRecommendationForm(Form):

    name = TextField('作品名称')
    remarks = TextField('审核备注')
    recomm_reason = TextField('推荐原因')

    cate_id = SelectField('作品类别',  coerce=int)
    status_id = SelectField('推荐状态',  coerce=int)
    user_id = SelectField('推荐人',   coerce=int)


class SignupForm(Form):

    """Form for send email"""
    email = TextField('邮箱', [DataRequired(message="邮箱不能为空"), Email(message="无效的邮箱")],
                      description='你常用的邮箱')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已经被注册过，请更换邮箱')

sharefun/__init__.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask import Flask, request, url_for, render_template, g, session, flash
from flask_wtf.csrf import CsrfProtect
from flask_debugtoolbar import DebugToolbarExtension
from flask.ext.login import LoginManager
from flask.ext.moment import Moment

from . import filters, permissions
from .utils import signout_user
from .config import load_config

config = load_config()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.signin'
login_manager.login_message = '请先登陆以获得相应操作权限'

# convert python's encoding to utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')


def register_login_manager(app):
    """注册login_manager"""
    login_manager.init_app(app)


def register_jinja(app):

    # inject vars into template context
    @app.context_processor
    def inject_vars():
        from .models import Category
        from datetime import date
        year = date.today().strftime("%Y")
        return dict(Permission=permissions.Permission, categories=Category.query.all(), year=year)

    # url generator for pagination
    def url_for_other_page(page):
        """Generate url for pagination"""
        view_args = request.view_args.copy()
        args = request.args.copy().to_dict()
        combined_args = dict(view_args.items() + args.items())
        combined_args['page'] = page
        return url_for(request.endpoint, **combined_args)
        # same effect
        # args = request.args.copy()
        # args['page'] = page
        # return url_for(request.endpoint, **args)

    app.jinja_env.globals['url_for_other_page'] = url_for_other_page


def register_routes(app):
    from .controllers import admin, site, user, auth
    app.register_blueprint(site.bp, url_prefix='')
    app.register_blueprint(admin.bp, url_prefix='/admin')
    app.register_blueprint(user.bp, url_prefix='/user')
    app.register_blueprint(auth.bp, url_prefix='/auth')


def register_error_handle(app):
    @app.errorhandler(403)
    def page_403(error):
        return render_template('site/403.html'), 403

    @app.errorhandler(404)
    def page_404(error):
        return render_template('site/404.html'), 404

    @app.errorhandler(405)
    def page_405(error):
        return render_template('site/405.html'), 405

    @app.errorhandler(500)
    def page_500(error):
        return render_template('site/500.html'), 500


def register_db(app):
    from .models import db
    db.init_app(app)


def register_mail(app):
    from .utils import mail
    mail.init_app(app)


def get_mail_handler():
    import logging
    from logging.handlers import SMTPHandler
    credentials = (config.SMTP_USER, config.SMTP_PASSWORD)
    mail_handler = SMTPHandler(config.SMTP_SERVER, config.SMTP_FROM,
                               config.SMTP_ADMIN, 'sf-log', credentials, ())
    from logging import Formatter
    mail_handler.setFormatter(Formatter('''
        Message type:       %(levelname)s
        Location:           %(pathname)s:%(lineno)d
        Module:             %(module)s
        Function:           %(funcName)s
        Time:               %(asctime)s

        Message:

        %(message)s
    '''))
    mail_handler.setLevel(logging.ERROR)
    return mail_handler


def register_logger(app):
    """send error log to admin by smtp"""
    if not app.debug:
        app.logger.addHandler(get_mail_handler())


def register_moment(app):
    moment = Moment(app)


def get_current_user():
    """获取当前user，同时进行session有效性的检测
       放在utils.py会造成环路引用
    """
    # 对应utils.py中signin_user方法
    # 豆瓣登陆则验证邮箱, 非豆瓣登陆不验证邮箱直接返回空值退出
    if 'signin_method' not in session:
        return None
    if 'user_id' not in session:
        return None
    # else:
    #     for k,v in session.iteritems():
    #         print k,v
    from .models import User
    # 此处是user_id而不是douban_id
    user = User.query.filter(User.id == session['user_id']).first()
    if not user:
        signout_user()
        return None
    return user


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # CSRF protect
    CsrfProtect(app)

    if app.debug:
        DebugToolbarExtension(app)

    register_jinja(app)
    register_routes(app)
    register_error_handle(app)
    register_db(app)
    register_logger(app)
    register_login_manager(app)
    register_moment(app)
    register_mail(app)

    app.jinja_env.filters['markdown'] = filters.markdown
    app.jinja_env.filters['normalize'] = filters.normalize
    app.jinja_env.filters[
        'engrolename_chinrolename'] = filters.engrolename_chinrolename
    app.jinja_env.filters['ismyself'] = filters.ismyself

    @app.before_request
    def before_request():
        g.user = get_current_user()
        if g.user:
            if not g.user.is_activated:
                flash('账户尚未激活，请先登陆' + g.user.email + '查收验证邮件并激活账户')
                signout_user()
            if g.user.is_banned:
                flash('账户已被禁用, 请联系管理员')
                signout_user()

    return app

app = create_app()

sharefun/config/__init__.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

import os


def load_config():
    """加载配置类"""
    mode = os.environ.get('MODE')
    try:
        if mode == 'PRODUCTION':
            from .production import ProductionConfig
            return ProductionConfig
        elif mode == 'TESTING':
            from .testing import TestingConfig
            return TestingConfig
        else:
            from .development import DevelopmentConfig
            return DevelopmentConfig
    except ImportError, e:
        from .default import Config
        return Config

sharefun/controllers/__init__.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

sharefun/controllers/admin.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask import Blueprint, render_template, redirect, url_for, request,  session, flash
from flask.ext.login import login_user, logout_user, login_required

from ..forms import SigninForm, RegisterForm, SingleRecommendationForm
from ..models import db, Status, Recommendation, User, Category, work_genres, Work
from ..decorators import admin_required, permission_required

import datetime

bp = Blueprint('admin', __name__)

# 判断是否具有某一特定权限
# @permission_required(Permission.MODERATE_COMMENTS)


@bp.route('/recommendations/audit/')
@login_required
@admin_required
def audit():
    statusids_recommendations = [
        (s.id, s.recommendations) for s in Status.query.order_by(Status.id)]
    return render_template('site/recommendations.html', statusids_recommendations=statusids_recommendations)


@bp.route('/recommendation/edit/<int:recomm_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_recommendation(recomm_id):
    recommendation = Recommendation.query.get_or_404(recomm_id)
    form = SingleRecommendationForm(obj=recommendation)
    form.cate_id.choices = [(t.id, t.name)
                            for t in Category.query.order_by(Category.index)]
    form.status_id.choices = [(t.id, t.name)
                              for t in Status.query.order_by(Status.id)]
    form.user_id.choices = [(t.id, t.username)
                            for t in User.query.order_by(User.id)]
    if form.validate_on_submit():
        recommendation.name = form.name.data
        recommendation.remarks = form.remarks.data
        recommendation.recomm_reason = form.recomm_reason.data
        recommendation.cate_id = form.cate_id.data
        recommendation.status_id = form.status_id.data
        recommendation.user_id = form.user_id.data
        recommendation.finished = datetime.datetime.utcnow()
        db.session.add(recommendation)
        db.session.commit()
        return redirect(url_for('admin.audit'))
    return render_template('site/recommendation.html', form=form, recommendation=recommendation)


@bp.route('/recommendations/audit/<int:recomm_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def audit_recommenations(recomm_id):
    recommendation = Recommendation.query.get_or_404(recomm_id)
    """审核与真正处理数据中间相隔一定时间，所以将审核通过状态分为通过未上架（默认）和通过已上架，增加删除待审核推荐"""
    if 'hide' in request.form:
        # 如果对应作品已上架则删除对应的work_genres和work数据，如需要再通过审核重新下载
        if recommendation.status_id == 3:
            work = Work.query.filter_by(id=recommendation.work_id).first()
            genres = work.genres
            for genre in genres:
                work.genres.remove(genre)
            db.session.delete(work)
            db.session.commit()
        recommendation.status_id = 5      # 设置为隐藏无效状态
    if 'yes' in request.form:
        recommendation.status_id = 2
    if 'no' in request.form:
        recommendation.status_id = 4
    if 'yes-append' in request.form:
        recommendation.remarks = recommendation.remarks + \
            request.form.get('remarks')
    elif 'yes-modify' in request.form:
        recommendation.remarks = request.form.get('remarks')
    recommendation.finished = datetime.datetime.utcnow()
    db.session.add(recommendation)
    db.session.commit()
    return redirect(url_for('admin.audit'))

sharefun/controllers/site.py
# -*- coding: utf-8 -*-

__author__ = 'frank'

from flask import render_template, Blueprint, redirect, url_for, request, flash, current_app
from flask.ext.login import current_user

from ..forms import WorkForm, CommentForm
from ..models import db, Category, Work, Comment, Recommendation, Status, User, Genre, work_genres

import os
from datetime import datetime

bp = Blueprint('site', __name__)


@bp.route('/')
def index():
    """首页"""
    newest_works = []
    categories = Category.query.order_by(Category.id).all()
    for category in categories:
        all_works = Work.query.filter_by(
            cate_id=category.id).order_by(Work.created.desc()).all()
        count = len(all_works)
        works = all_works[:4] if len(all_works) >= 4 else all_works+['']*(4-len(all_works))
        newest_works.append([category, [count, works]])
    newest_comments = Comment.query.order_by(Comment.created.desc()).limit(5)
    total = Recommendation.query.count()
    success = Recommendation.query.filter(
        Recommendation.status_id == 3).count()
    failure = Recommendation.query.filter(
        Recommendation.status_id == 4).count()
    return render_template('site/index.html', newest_works=newest_works, newest_comments=newest_comments, current_time=datetime.utcnow(), total=total, success=success, failure=failure)


@bp.route('/category')
def category():
    """分类页"""
    genre_id = request.args.get('genre_id', 0, int)
    page = request.args.get('page', 1, int)
    cate_id = request.args.get('cate_id', 1, int)
    works = Work.query.filter_by(cate_id=cate_id)
    # 按照类型对应的作品数对类型排序
    from sqlalchemy import func
    genres = [genre for genre, count in db.session.query(Genre, func.count(work_genres.c.work_id).label(
        'total')).filter_by(cate_id=cate_id).join(work_genres).group_by(Genre).order_by('total desc').all()]
    if genre_id:
        if genre_id == -1:  # 随机
            works = works.order_by(func.rand())
        else:
            # use join
            # works = works.join(Genre.works).filter(Genre.id == genre_id)
            works = works.filter(Work.genres.any(id=genre_id)).order_by(
                Work.created.desc())
    else:
        works = works.order_by(Work.created.desc())

    # newest_comments = Comment.query.order_by(Comment.created.desc()).limit(5)
    newest_comments = Comment.query.join(Work).filter_by(cate_id=cate_id).order_by(Comment.created.desc()).limit(5)
    total = Recommendation.query.count()
    success = Recommendation.query.filter(
        Recommendation.status_id == 3).count()
    failure = Recommendation.query.filter(
        Recommendation.status_id == 4).count()
    works = works.paginate(
        page, current_app.config['FLASK_WORKS_PER_PAGE'], error_out=True)
    return render_template('site/category.html', works=works, newest_comments=newest_comments, current_time=datetime.utcnow(), total=total, success=success, failure=failure, genres=genres, genre_id=genre_id, page=page, cate_id=cate_id)


@bp.route('/about')
def about():
    """关于"""
    return render_template('site/about.html')


@bp.route('/work/<int:work_id>', methods=['GET', 'POST'])
def work(work_id):
    """详情页"""
    form = CommentForm()
    q = Work.query
    work = q.get_or_404(work_id)
    prev = q.filter(Work.id > work_id).order_by(Work.id).first()
    next = q.filter(Work.id < work_id).order_by(Work.id.desc()).first()
    genres = []
    for genre in work.genres:
        genres.append(genre)
    if form.validate_on_submit() and current_user.is_authenticated():
        content = form.content.data.strip()
        comment = Comment(
            content=content, user_id=current_user.id,  work_id=work.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('site.work', work_id=work.id))
    return render_template('site/work.html', work=work, form=form, genres=genres, prev=prev, next=next)


@bp.route('/user/<int:id>')
def user(id):
    user = User.query.get_or_404(id)
    success_recomms_count = Recommendation.query.filter(
        Recommendation.user_id == id, Recommendation.status_id == 3).count()
    comments_count = Comment.query.filter(Comment.user_id == id).count()
    return render_template('site/user.html', user=user, success_recomms_count=success_recomms_count, comments_count=comments_count)


@bp.route('/comments')
def comments():
    """所有评论页"""
    user_id = request.args.get('user_id', 0, int)
    page = request.args.get('page', 1, int)
    comments = Comment.query.order_by(Comment.created.desc())
    # 只显示有评论的user
    users = [user for user in User.query.all() if user.comments.count()]
    # 按照评论数量倒序对user排序
    users = sorted(
        users, lambda u1, u2: cmp(u1.comments.count(), u2.comments.count()), reverse=True)
    if user_id:
        comments = comments.filter(Comment.user_id == user_id)
    comments = comments.paginate(
        page, current_app.config['FLASK_COMMENTS_PER_PAGE'], error_out=True)
    return render_template('site/comments.html', comments=comments, users=users, user_id=user_id)


@bp.route('/recommendations')
def recommendations():
    statusids_recommendations = [
        (s.id, s.recommendations) for s in Status.query.order_by(Status.id)]
    return render_template('site/recommendations.html', statusids_recommendations=statusids_recommendations)


@bp.route('/search')
def search():
    keyword = request.args.get('keyword')
    if not keyword:
        flash('请输入要在本站搜索的作品名称')
        return redirect(url_for('site.index'))
    else:
        works = Work.query.filter(Work.title.like('%' + keyword + '%'))
        if not works.count():
            flash('抱歉，本站暂未收录与"' + keyword + '"相关的作品')
            return redirect(url_for('site.index'))
        else:
            return render_template('site/search.html', works=works, keyword=keyword)

sharefun/script/__init__.py
from ..config import load_config

config = load_config()

sharefun/templates/site/405.html
{% extends "layout.html" %}

{% block page_title %}405{% endblock %}
{% block page_id %}page-405-error{% endblock %}

{% block body %}

   <h3>提示</h3>

   <p>抱歉，请先退出当前登陆账户后再进行相应操作！！</p>

{% endblock %}

sharefun/templates/site/category.html
{% extends "layout.html" %}
{% from "macro/common.html" import pagination %}

{% block page_title %}享乐-首页{% endblock %}
{% block page_id %}page-index{% endblock %}

{% block body %}
    {# <legend>全部作品</legend> #}
    <div class="row">
        {# The local date and time is {{ moment(current_time).format('LLL') }}. #}
        {# <p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>. #}
        <div class='col-md-9'>
            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
            <div class="genres-selector">
                <a href="{{ url_for('site.category', cate_id=cate_id) }}" class="genre all {% if not genre_id %}on{% endif %} ">全部</a>
                <a href="{{ url_for('site.category', genre_id=-1, cate_id=cate_id) }}" class="genre random {% if genre_id == -1 %}on{% endif %} ">随机</a>
                {% for genre in genres %}
                    <a href="{{ url_for('site.category', genre_id=genre.id, cate_id=genre.cate_id) }}" class="genre {% if genre.id == genre_id %}on{% endif %}">{{ genre.name }}</a>
                {% endfor %}
            </div>
             <div class='works-wap'>
                {% if not works.items %}
                    暂无
                {% endif %}
                {% for work in works.items %}
                    <div class='work-item'>
                        <a href="{{ url_for('site.work', work_id=work.id) }}">
                            {% if work.cate_id == 2 %}
                                <img class="cover img-responsive" src="{{ work.cover_url }}" title="{{ work.title }}" alt="{{ work.title }}">
                            {% else %}
                                <img class="cover img-responsive" src="{{ url_for('static', filename='%s' % work.cover_path) }}" title="{{ work.title }}" alt="{{ work.title }}">
                            {% endif %}
                            <p class='title'>{{ work.title }}</p>
                            {% if work.cate_id == 2 %}
                                <p class='author'>{{ work.author }}</p>
                            {% else %}
                                <p class='director'>{{ work.director }}</p>
                            {% endif %}
                        </a>
                    </div>
                {% endfor%}
            </div>
            {{ pagination(works) }}
        </div>
        <div class='col-md-3'>
             <div class="statistics">
                <p>共{{ total }}个推荐</p>
                <p> {{ success }}个已成功上架,{{ failure }}个未通过审核</p>
             </div>
             <div class='comments-section'>
                <div class="comments-header">
                    最近评论(<a href="{{ url_for('site.comments') }}">所有评论</a>)
                </div>
                <div class="comments-wap">
                    {% if newest_comments.count() > 0 %}
                        {% for comment in newest_comments %}
                            <div class="comment-item">
                                <div class="comment-info">
                                    <div class="comment-username-created">
                                        <li class="comment-username"><a href="{{ url_for('site.user', id=comment.user_id) }}" target="_blank">{{ comment.user.username | ismyself | normalize }}</a></li>
                                        <li> &nbsp;于&nbsp; </li>
                                        <li>{{ moment(comment.created).fromNow(refresh=True) }}</li>
                                    </div>
                                    <div class="comement-workname">
                                        在《<a href="{{ url_for('site.work', work_id=comment.work.id) }}" target="_blank">{{ comment.work.title }}</a>》发表评论：

                                    </div>
                                </div>
                                <div class="comment-content">
                                    {{ comment.content | markdown | safe }}
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        暂无
                    {% endif %}
                </div>
             </div>
        </div>
    </div>
{% endblock %}

sharefun/templates/site/comments.html
{% extends "layout.html" %}
{% from "macro/common.html" import pagination %}

{% block page_title %}享乐-所有评论页{% endblock %}
{% block page_id %}page-comments{% endblock %}

{% block body %}
    <div class="col-md-8">
        <div class="users-selector">
            <a class="user all {% if not user_id %}on{% endif %}" href="{{ url_for('site.comments') }}">全部</a>
            {% for user in users %}
                <a class="user {% if user.id == user_id %}on{% endif %}" href="{{ url_for('site.comments', user_id=user.id) }}">{{ user.username }}</a>
            {% endfor %}
        </div>
        <div class="comments-wap">
            {% if not comments.items %}
                暂无
            {% else %}
                {% for comment in comments.items %}
                    <div class="comment-item">
                        <div class="comment-content">
                            {{ comment.content | markdown | safe }}
                        </div>
                        <div class="comment-info">
                            <li class="comment-username"><a href="{{ url_for('site.user', id=comment.user_id) }}" target="_blank">{{ comment.user.username | ismyself | normalize }}</a></li>
                            <li>&nbsp;</li>
                            <li class="comment-created">{{ moment(comment.created).fromNow(refresh=True) }}</li>
                            <li>&nbsp;</li>
                            <li class="comment-workname">《<a href="{{ url_for('site.work', work_id=comment.work.id) }}" target="_blank">{{ comment.work.title }}</a>》</li>
                        </div>
                    </div>
                    <hr/>
                {% endfor %}
            {% endif %}
        </div>
        {{ pagination(comments) }}
    </div>
{% endblock %}

sharefun/templates/site/index.html
{% extends "layout.html" %}
{% from "macro/common.html" import pagination %}

{% block page_title %}享乐-首页{% endblock %}
{% block page_id %}page-index{% endblock %}

{% block body %}
    {# <legend>全部作品</legend> #}
    <div class="row">
        {# The local date and time is {{ moment(current_time).format('LLL') }}. #}
        {# <p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>. #}
        <div class='col-md-9'>
            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
            <div class="genres-selector">
                <a href="{{ url_for('site.index', cate_id=cate_id) }}" class="genre all {% if not genre_id %}on{% endif %} ">全部</a>
                <a href="{{ url_for('site.index', genre_id=-1, cate_id=cate_id) }}" class="genre random {% if genre_id == -1 %}on{% endif %} ">随机</a>
                {% for genre in genres %}
                    <a href="{{ url_for('site.index', genre_id=genre.id, cate_id=genre.cate_id) }}" class="genre {% if genre.id == genre_id %}on{% endif %}">{{ genre.name }}</a>
                {% endfor %}
            </div>
             <div class='works-wap'>
                {% if not works.items %}
                    暂无
                {% endif %}
                {% for work in works.items %}
                    <div class='work-item'>
                        <a href="{{ url_for('site.work', work_id=work.id) }}">
                            {% if work.cate_id == 2 %}
                                <img class="cover img-responsive" src="{{ work.cover_url }}" title="{{ work.title }}" alt="{{ work.title }}">
                            {% else %}
                                <img class="cover img-responsive" src="{{ url_for('static', filename='%s' % work.cover_path) }}" title="{{ work.title }}" alt="{{ work.title }}">
                            {% endif %}
                            <p class='title'>{{ work.title }}</p>
                            {% if work.cate_id == 2 %}
                                <p class='author'>{{ work.author }}</p>
                            {% else %}
                                <p class='director'>{{ work.director }}</p>
                            {% endif %}
                        </a>
                    </div>
                {% endfor%}
            </div>
            {{ pagination(works) }}
        </div>
        <div class='col-md-3'>
             <div class="statistics">
                <p>共{{ total }}个推荐</p>
                <p> {{ success }}个已成功上架,{{ failure }}个未通过审核</p>
             </div>
             <div class='comments-section'>
                <div class="comments-header">
                    最近评论(<a href="{{ url_for('site.comments') }}">所有评论</a>)
                </div>
                <div class="comments-wap">
                    {% if newest_comments.count() > 0 %}
                        {% for comment in newest_comments %}
                            <div class="comment-item">
                                <div class="comment-info">
                                    <div class="comment-username-created">
                                        <li class="comment-username"><a href="{{ url_for('site.user', id=comment.user_id) }}" target="_blank">{{ comment.user.username | ismyself | normalize }}</a></li>
                                        <li> &nbsp;于&nbsp; </li>
                                        <li>{{ moment(comment.created).fromNow(refresh=True) }}</li>
                                    </div>
                                    <div class="comement-workname">
                                        在《<a href="{{ url_for('site.work', work_id=comment.work.id) }}" target="_blank">{{ comment.work.title }}</a>》发表评论：

                                    </div>
                                </div>
                                <div class="comment-content">
                                    {{ comment.content | markdown | safe }}
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        暂无
                    {% endif %}
                </div>
             </div>
        </div>
    </div>
{% endblock %}

sharefun/templates/site/recommendation.html
{% extends "layout.html" %}
{% from "macro/common.html" import field_errors, horizontal_field %}

{% block page_title %}享乐-推荐页
{% endblock %}
{% block page_id %}page-recommendation
{% endblock %}

{% block body %}
    <div class="row">
        <legend>修改推荐页面</legend>
        <div class='col-md-8'>
            <form id="form-edit-recommendation" class="form-horizontal" method="POST" action="{{ url_for('admin.edit_recommendation', recomm_id=recommendation.id) }}">
                <fieldset>
                    {{ form.csrf_token }}

                    {{ horizontal_field(form.name, length=5) }}
                    {{ horizontal_field(form.remarks, length=5) }}
                    {{ horizontal_field(form.recomm_reason, length=5) }}

                    {{ horizontal_field(form.cate_id, length=5) }}
                    {{ horizontal_field(form.status_id, length=5) }}
                    {{ horizontal_field(form.user_id, length=5) }}

                    <div class="form-group">
                        <div class="col-md-3 col-md-offset-2">
                            <input type="submit" value="提交" class="btn btn-sm btn-primary" />
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>

    </div>
{% endblock %}